Resources:
  helloworldendpointServiceRoleB6E2B862:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-endpoint/ServiceRole/Resource
  helloworldendpoint3282B657:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2dS3BucketF7EFCE1F
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2dS3VersionKey1B0E35E0
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2dS3VersionKey1B0E35E0
      Handler: handler.handler
      Role:
        Fn::GetAtt:
          - helloworldendpointServiceRoleB6E2B862
          - Arn
      Runtime: nodejs10.x
    DependsOn:
      - helloworldendpointServiceRoleB6E2B862
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-endpoint/Resource
      aws:asset:path: /Users/ctrimble/git/cdk-sam-example/dist
      aws:asset:property: Code
  helloworldapi61D4D3D5:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: GraphQL based hello world
      Name: Hello World API
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-api/Resource
  helloworldapiDeployment10C17DEE9ffbeeb3ee9f1b38ab7eb9f67477aea6:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: helloworldapi61D4D3D5
      Description: Automatically created by the RestApi construct
    DependsOn:
      - helloworldapiPOST6E08AD4A
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-api/Deployment/Resource
  helloworldapiDeploymentStageprodA60249BE:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: helloworldapi61D4D3D5
      DeploymentId:
        Ref: helloworldapiDeployment10C17DEE9ffbeeb3ee9f1b38ab7eb9f67477aea6
      StageName: prod
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-api/DeploymentStage.prod/Resource
  helloworldapiCloudWatchRole720B1846:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-api/CloudWatchRole/Resource
  helloworldapiAccount1363D8B0:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - helloworldapiCloudWatchRole720B1846
          - Arn
    DependsOn:
      - helloworldapi61D4D3D5
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-api/Account
  helloworldapiPOSTApiPermissionHelloWorldStackhelloworldapi2A775805POSTF639038A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - helloworldendpoint3282B657
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: helloworldapi61D4D3D5
            - /
            - Ref: helloworldapiDeploymentStageprodA60249BE
            - /POST/
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-api/Default/POST/ApiPermission.HelloWorldStackhelloworldapi2A775805.POST..
  helloworldapiPOSTApiPermissionTestHelloWorldStackhelloworldapi2A775805POST1209FC14:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - helloworldendpoint3282B657
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: helloworldapi61D4D3D5
            - /test-invoke-stage/POST/
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-api/Default/POST/ApiPermission.Test.HelloWorldStackhelloworldapi2A775805.POST..
  helloworldapiPOST6E08AD4A:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Fn::GetAtt:
          - helloworldapi61D4D3D5
          - RootResourceId
      RestApiId:
        Ref: helloworldapi61D4D3D5
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - helloworldendpoint3282B657
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: HelloWorldStack/hello-world-api/Default/POST/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.36.1,@aws-cdk/assets=1.36.1,@aws-cdk/aws-apigateway=1.36.1,@aws-cdk/aws-cloudwatch=1.36.1,@aws-cdk/aws-ec2=1.36.1,@aws-cdk/aws-events=1.36.1,@aws-cdk/aws-iam=1.36.1,@aws-cdk/aws-kms=1.36.1,@aws-cdk/aws-lambda=1.36.1,@aws-cdk/aws-logs=1.36.1,@aws-cdk/aws-s3=1.36.1,@aws-cdk/aws-s3-assets=1.36.1,@aws-cdk/aws-sqs=1.36.1,@aws-cdk/aws-ssm=1.36.1,@aws-cdk/cloud-assembly-schema=1.36.1,@aws-cdk/core=1.36.1,@aws-cdk/cx-api=1.36.1,@aws-cdk/region-info=1.36.1,jsii-runtime=node.js/v12.15.0
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersc357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2dS3BucketF7EFCE1F:
    Type: String
    Description: S3 bucket for asset "c357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2d"
  AssetParametersc357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2dS3VersionKey1B0E35E0:
    Type: String
    Description: S3 key for asset version "c357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2d"
  AssetParametersc357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2dArtifactHash38DD70ED:
    Type: String
    Description: Artifact hash for asset "c357f910f794164977fa37a9452d15ce03c52694c19e42703fa82a9da7a26b2d"
Outputs:
  helloworldapiEndpoint9A31576C:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: helloworldapi61D4D3D5
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: helloworldapiDeploymentStageprodA60249BE
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

